# This file generates the GitHub Actions matrix.
include:
   - board: nice_nano_v2
     shield: kiwi-v4_left
   - board: nice_nano_v2
     shield: kiwi-v4_right
   - board: nice_nano_v2
     shield: settings_reset
