manifest:
  remotes:
    - name: origin 
      url-base: https://github.com/MaxwellMiddendorf/
  projects:
    - name: kiwi-v4
      remote: origin
      revision: master 
      import: config/zmk/app/west.yml
  self:
    path: config
