manifest:
  remotes:
    - name: maxwellmiddendorf 
      url-base: https://github.com/MaxwellMiddendorf/ 
  projects:
    - name: kiwi-v4
      remote: MaxwellMiddendorf
      revision: main
      import: config/zmk/app/west.yml
  self:
    path: config
